language: python
python: 3.6.5

services:
  - mysql

env:
  -DJANGO=1.11 DB=mysql

install:
  - pip install pipenv
  - pipenv install
  - python -m pip install coveralls

before_script:
  - mysql -e 'create database test;' -u root

jobs:
  include:
    - stage: unit
      script: coverage run --source='.' manage.py test moviemancer

after_success:
  - coveralls