language: python
python: 3.6.5
cache: pip

services:
  - postgres

install:
  - pip install pipenv
  - pipenv lock -r --dev >> requirements.txt
  - pip install -r requirements.txt
  - python -m pip install coveralls

before_script:
  - psql -c "CREATE DATABASE mydb;" -U postgres

jobs:
  include:
    - stage: unit
      script: coverage run --source='.' manage.py test moviemancer

after_script:
  - rm .coverage

after_success:
  - coveralls